from typing import Any

class CThostFtdcMdSpi: ...


class CThostFtdcReqUserLoginField: ...


class CThostFtdcMdApi:
    @staticmethod
    def CreateFtdcMdApi(psFlowPath: str | None = None) -> "CThostFtdcMdApi": ...

    def RegisterFront(self, pszFrontAddress: str) -> None: ...
    def RegisterSpi(self, pSpi: object) -> None: ...
    def Init(self) -> int: ...
    def Join(self) -> int: ...
    def Release(self) -> None: ...
    def ReqUserLogin(
        self,
        pReqUserLoginField: CThostFtdcReqUserLoginField,
        nRequestID: int,
    ) -> int: ...
    def SubscribeMarketData(self, ppInstrumentID: list[str], nCount: int) -> int: ...
    def UnSubscribeMarketData(
        self,
        ppInstrumentID: list[str],
        nCount: int,
    ) -> int: ...


def __getattr__(name: str) -> Any: ...
