"""导出交易渠道插件契约与进程内注册表 API."""

from axile.channels.contracts import (
    AlgorithmReference,
    ChannelAccountField,
    ChannelAccountFieldClipboard,
    ChannelAccountFieldCondition,
    ChannelAccountFieldConstraints,
    ChannelAccountForm,
    ChannelAccountNotice,
    ChannelAccountOption,
    ChannelCalendar,
    ChannelDefaults,
    ChannelDescriptor,
    ChannelEndpointConstraints,
    ChannelLeverage,
    ChannelNumberConstraints,
    ChannelPlugin,
    ChannelPortfolioPreset,
    ChannelUi,
    ChannelUnits,
    ExecutionBackend,
)
from axile.channels.registry import (
    ENTRY_POINT_GROUP,
    ChannelPluginLoadError,
    DuplicateChannelError,
    get_channel,
    list_channels,
    register_channel,
)

__all__ = [
    "ENTRY_POINT_GROUP",
    "AlgorithmReference",
    "ChannelAccountField",
    "ChannelAccountFieldClipboard",
    "ChannelAccountFieldCondition",
    "ChannelAccountFieldConstraints",
    "ChannelAccountForm",
    "ChannelAccountNotice",
    "ChannelAccountOption",
    "ChannelCalendar",
    "ChannelDefaults",
    "ChannelDescriptor",
    "ChannelLeverage",
    "ChannelEndpointConstraints",
    "ChannelNumberConstraints",
    "ChannelPlugin",
    "ChannelPortfolioPreset",
    "ChannelUi",
    "ChannelUnits",
    "ChannelPluginLoadError",
    "DuplicateChannelError",
    "ExecutionBackend",
    "get_channel",
    "list_channels",
    "register_channel",
]
