"""服务端数据库模型聚合入口."""

from __future__ import annotations

from sqlmodel import SQLModel

from axile.server.db.models.account import (
    Account,
    AccountBase,
    AccountCreate,
    AccountDashboardItemPublic,
    AccountDashboardPublic,
    AccountListPublic,
    AccountNextRunPublic,
    AccountPublic,
    AccountUpdate,
    PortfolioAccount,
    PortfolioAccountBase,
    PortfolioAccountListPublic,
    PortfolioAccountPublic,
)
from axile.server.db.models.account_control import (
    AccountControlAuditExecutionListPublic,
    AccountControlAuditExecutionPublic,
    AccountControlAuditSummaryPublic,
    AccountControlCounterDelta,
    AccountControlCounterDeltaBase,
    AccountControlEvent,
    AccountControlEventBase,
    AccountControlEventListPublic,
    AccountControlEventPublic,
)
from axile.server.db.models.base import PydanticJSONType, new_execution_id, now_ms, now_str
from axile.server.db.models.execution import (
    ExecuteRecord,
    ExecuteRecordBase,
    ExecuteRecordListPublic,
    ExecuteRecordPublic,
    ExecutionArtifact,
    ExecutionArtifactBase,
    ExecutionArtifactListPublic,
    ExecutionArtifactPublic,
    ExecutionEvent,
    ExecutionEventBase,
    ExecutionEventListPublic,
    ExecutionEventPublic,
    ExecutionStatusPublic,
    ExecutionTerminateRequest,
    ExecutionTerminateResponse,
    ExecutionTriggerResponse,
    ListResponse,
    ListResponsePage,
    Message,
)
from axile.server.db.models.portfolio import (
    Portfolio,
    PortfolioBase,
    PortfolioCreate,
    PortfolioListPublic,
    PortfolioLitePublic,
    PortfolioPreviewRequest,
    PortfolioPublic,
    PortfolioUpdate,
    StrategyConfig,
    StrategyConfigBase,
    StrategyConfigListPublic,
    StrategyConfigPublic,
    ValidateCustomCalcRequest,
    ValidateCustomCalcResponse,
)
from axile.server.db.models.trading_calendar import TradingCalendarRecord

StrategyConfig.model_rebuild()
Portfolio.model_rebuild()
Account.model_rebuild()
PortfolioAccount.model_rebuild()
ExecuteRecord.model_rebuild()

__all__ = [
    "SQLModel",
    "PydanticJSONType",
    "now_str",
    "now_ms",
    "new_execution_id",
    "StrategyConfigBase",
    "StrategyConfig",
    "StrategyConfigPublic",
    "StrategyConfigListPublic",
    "PortfolioBase",
    "Portfolio",
    "PortfolioUpdate",
    "PortfolioCreate",
    "PortfolioPreviewRequest",
    "PortfolioPublic",
    "PortfolioLitePublic",
    "PortfolioListPublic",
    "ValidateCustomCalcRequest",
    "ValidateCustomCalcResponse",
    "AccountBase",
    "AccountCreate",
    "Account",
    "AccountPublic",
    "AccountListPublic",
    "AccountNextRunPublic",
    "AccountDashboardItemPublic",
    "AccountDashboardPublic",
    "AccountUpdate",
    "PortfolioAccountBase",
    "PortfolioAccount",
    "PortfolioAccountPublic",
    "PortfolioAccountListPublic",
    "ExecuteRecordBase",
    "ExecuteRecord",
    "ExecuteRecordPublic",
    "ExecuteRecordListPublic",
    "ExecutionEventBase",
    "ExecutionEvent",
    "ExecutionEventPublic",
    "ExecutionEventListPublic",
    "ExecutionArtifactBase",
    "ExecutionArtifact",
    "ExecutionArtifactPublic",
    "ExecutionArtifactListPublic",
    "AccountControlCounterDeltaBase",
    "AccountControlCounterDelta",
    "AccountControlEventBase",
    "AccountControlEvent",
    "AccountControlAuditSummaryPublic",
    "AccountControlAuditExecutionPublic",
    "AccountControlAuditExecutionListPublic",
    "AccountControlEventPublic",
    "AccountControlEventListPublic",
    "ExecutionTriggerResponse",
    "ExecutionTerminateRequest",
    "ExecutionTerminateResponse",
    "ExecutionStatusPublic",
    "Message",
    "ListResponse",
    "ListResponsePage",
    "TradingCalendarRecord",
]
