import { expect, test, type Page } from '@playwright/test'

async function replace(page: Page, code: string) {
  await page.locator('.cm-content').first().click()
  await page.keyboard.press('ControlOrMeta+a')
  await page.keyboard.insertText(code)
}

test.beforeEach(async ({ page }) => {
  page.on('pageerror', (error) => { throw error })
  await page.goto('/e2e/editor.html')
  await expect(page.getByRole('status', { name: '语言服务' })).toHaveAttribute('data-state', 'ready')
})

test('editing, search, formatting and undo preserve text', async ({ page }) => {
  await replace(page, 'values={"中文":1}\n')
  await page.getByRole('button', { name: '格式化', exact: true }).click()
  await expect(page.getByTestId('code')).toHaveText('values = {"中文": 1}\n')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.getByTestId('code')).toHaveText('values={"中文":1}\n')
  await page.getByRole('button', { name: '重做', exact: true }).click()
  await expect(page.getByTestId('code')).toHaveText('values = {"中文": 1}\n')
  await page.getByRole('button', { name: '查找 / 替换' }).click()
  await expect(page.locator('.cm-search')).toBeVisible()
  await page.locator('.cm-search input[name=search]').fill('values')
  await page.locator('.cm-search input[name=replace]').fill('prices')
  await page.getByRole('button', { name: '全部替换', exact: true }).click()
  await expect(page.getByTestId('code')).toContainText('prices')
})

test('completion, diagnostics, semantic tokens, hints and folding', async ({ page }) => {
  await expect(page.locator('.cm-python-inlay').first()).toBeVisible()
  await expect(page.locator('.cm-python-semantic-function').first()).toBeVisible()
  await page.screenshot({ path: 'test-results/python-editor-light.png', fullPage: true })
  await page.evaluate(() => document.documentElement.classList.add('dark'))
  await expect(page.locator('.cm-editor').first()).toHaveCSS('background-color', 'rgb(10, 15, 20)')
  await page.screenshot({ path: 'test-results/python-editor-dark.png', fullPage: true })
  await expect(page.locator('.cm-foldGutter .cm-gutterElement').filter({ hasText: '⌄' }).first()).toBeVisible()
  await page.locator('.cm-foldGutter .cm-gutterElement').filter({ hasText: '⌄' }).first().click()
  await expect(page.locator('.cm-foldPlaceholder')).toBeVisible()
  await page.locator('.cm-foldPlaceholder').click()
  await replace(page, 'from axile.server.context import Context\ndef calculate_portfolio(context: Context):\n    context.get_')
  await page.keyboard.press('Control+Space')
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('get_price')
  await page.keyboard.press('Escape')
  await replace(page, 'wrong: int = "中文😀"\n')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
  await replace(page, 'wrong: int = 1\n')
  await expect(page.getByTestId('problems')).toHaveText('[]')
})

test('auto-import completion inserts an import and is undoable', async ({ page }) => {
  await replace(page, 'path = Pat')
  await page.keyboard.press('Control+Space')
  const option = page.locator('.cm-tooltip-autocomplete li').filter({ hasText: /Path.*pathlib/ }).first()
  await expect(option).toBeVisible()
  await option.click()
  await expect(page.getByTestId('code')).toContainText('from pathlib import Path')
  await expect(page.getByTestId('code')).toContainText('path = Path')
  await page.keyboard.press('ControlOrMeta+z')
  await expect(page.getByTestId('code')).toHaveText('path = Pat')
})

test('a delayed formatter cannot overwrite newer typing', async ({ page }) => {
  let finish: () => void = () => {}
  const waiting = new Promise<void>((resolve) => { finish = resolve })
  await page.route('**/editor/format', async (route) => {
    await waiting
    await route.fulfill({ json: { code: 'value = 1\n' } })
  })
  await replace(page, 'value=1')
  await page.getByRole('button', { name: '格式化', exact: true }).click()
  await expect(page.getByRole('button', { name: '格式化中…' })).toBeDisabled()
  await replace(page, 'value=2')
  finish()
  await expect(page.getByText('代码已变化，请重新格式化')).toBeVisible()
  await expect(page.getByTestId('code')).toHaveText('value=2')
})

test('definition opens read-only source and rename is undoable', async ({ page }) => {
  await page.locator('.cm-content').first().click()
  await page.keyboard.press('ControlOrMeta+Home')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Home')
  for (let i = 0; i < 24; i++) await page.keyboard.press('ArrowRight')
  await page.keyboard.press('F12')
  await expect(page.getByRole('dialog', { name: '只读源码预览' })).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('context.py')
  await expect(page.getByRole('dialog').locator('.cm-content')).toHaveAttribute('contenteditable', 'false')
  await page.keyboard.press('Escape')
  await expect(page.locator('.cm-content').first()).toBeFocused()
  await page.keyboard.press('Home')
  for (let i = 0; i < 2; i++) await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Shift+F12')
  await expect(page.locator('.cm-lsp-reference')).toHaveCount(2)
  await page.keyboard.press('Escape')
  await page.keyboard.press('F2')
  await page.locator('input[name=name]').fill('latest_price')
  await page.getByRole('button', { name: '重命名', exact: true }).last().click()
  await expect(page.getByTestId('code')).toContainText('latest_price')
  await page.keyboard.press('ControlOrMeta+z')
  await expect(page.getByTestId('code')).not.toContainText('latest_price')
})

test('hover, signature help and quick fixes use ty results', async ({ page }) => {
  await page.locator('.cm-python-semantic-method, .cm-python-semantic-function').filter({ hasText: /^get_price$/ }).hover()
  await expect(page.locator('.cm-tooltip')).toContainText('get_price')
  await replace(page, 'from axile.server.context import Context\ndef calculate_portfolio(context: Context):\n    context.get_price')
  await page.keyboard.type('(')
  await expect(page.locator('.cm-tooltip')).toContainText('symbol')
  await replace(page, 'wrong: int = "bad"')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
  await page.getByRole('button', { name: '快速修复', exact: true }).click()
  const fixes = page.locator('form[aria-label="快速修复"] button')
  await expect(fixes.first()).toBeVisible()
  await fixes.first().click()
  await expect(page.getByTestId('code')).not.toHaveText('wrong: int = "bad"')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.getByTestId('code')).toHaveText('wrong: int = "bad"')
})

test('runtime diagnostics coexist with ty and expire after editing', async ({ page }) => {
  await replace(page, 'wrong: int = "bad"')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
  await page.keyboard.press('ControlOrMeta+Enter')
  await expect(page.getByTestId('problems')).toContainText('模拟试跑错误')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
  await page.keyboard.type(' ')
  await expect(page.getByTestId('problems')).not.toContainText('模拟试跑错误')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
})

test('indentation, bracket pairing, comment and multi-selection shortcuts', async ({ page }) => {
  await replace(page, 'def example():')
  await page.keyboard.press('Enter')
  await page.keyboard.type('value = (')
  await expect(page.getByTestId('code')).toHaveText('def example():\n    value = ()')
  await page.keyboard.press('ControlOrMeta+/')
  await expect(page.getByTestId('code')).toContainText('# value = ()')
  await replace(page, 'value = 1\nother = value')
  await page.keyboard.press('ControlOrMeta+Home')
  await page.keyboard.press('ControlOrMeta+d')
  await page.keyboard.press('ControlOrMeta+d')
  await page.keyboard.insertText('price')
  await expect(page.getByTestId('code')).toHaveText('price = 1\nother = price')
})

test('reconnect resynchronizes unsaved text without losing undo', async ({ page, request }) => {
  await replace(page, 'draft: int = "keep me"\n')
  await request.post('http://127.0.0.1:1439/test/disconnect')
  await expect(page.getByRole('status', { name: '语言服务' })).toHaveAttribute('data-state', 'reconnecting')
  await expect(page.getByRole('status', { name: '语言服务' })).toHaveAttribute('data-state', 'ready', { timeout: 20000 })
  await expect(page.getByTestId('code')).toHaveText('draft: int = "keep me"\n')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
  await page.getByRole('button', { name: '撤销', exact: true }).click()
  await expect(page.getByTestId('code')).not.toContainText('keep me')
})
