import { expect, test, type Page } from '@playwright/test'

async function replace(page: Page, code: string) {
  await page.locator('.cm-content').first().click()
  await page.keyboard.press('ControlOrMeta+a')
  await page.keyboard.insertText(code)
}

async function editorCommand(page: Page, name: string) {
  await page.getByRole('button', { name: '菜单', exact: true }).click()
  await page.getByRole('menuitem', { name, exact: true }).click()
}

test.beforeEach(async ({ page }) => {
  page.on('pageerror', (error) => { throw error })
  await page.goto('/e2e/editor.html')
  await expect(page.getByRole('status', { name: '代码分析器' })).toHaveAttribute('data-state', 'ready')
})

test('document symbols navigate to the current function and class method', async ({ page }) => {
  await replace(page, 'class Strategy:\n    def calculate(self):\n        return 1\n\ndef another():\n    return 2\n')
  await expect(page.getByRole('button', { name: '目标函数' })).toBeVisible()
  await page.getByRole('button', { name: '目标函数' }).click()
  await expect(page.getByRole('menuitem', { name: /Strategy/ })).toBeVisible()
  await page.getByRole('menuitem', { name: /Strategy/ }).click()
  await expect(page.getByRole('button', { name: 'Strategy' })).toBeVisible()
  await page.locator('.cm-content').click()
  await page.keyboard.press('ControlOrMeta+End')
  await page.keyboard.press('ArrowUp')
  await expect(page.getByRole('button', { name: 'another' })).toBeVisible()
})

test('editing, search, formatting and undo preserve text', async ({ page }) => {
  await replace(page, 'values={"中文":1}\n')
  await page.getByRole('button', { name: '格式化', exact: true }).click()
  await expect(page.getByTestId('code')).toHaveText('values = {"中文": 1}\n')
  await editorCommand(page, '撤销')
  await expect(page.getByTestId('code')).toHaveText('values={"中文":1}\n')
  await editorCommand(page, '重做')
  await expect(page.getByTestId('code')).toHaveText('values = {"中文": 1}\n')
  await editorCommand(page, '查找 / 替换')
  await expect(page.locator('.cm-search')).toBeVisible()
  await page.locator('.cm-search input[name=search]').fill('values')
  await page.locator('.cm-search input[name=replace]').fill('prices')
  await page.getByRole('button', { name: '全部替换', exact: true }).click()
  await expect(page.getByTestId('code')).toContainText('prices')
})

test('completion, diagnostics, semantic tokens, hints and folding', async ({ page }) => {
  await expect(page.locator('.cm-python-inlay').first()).toBeVisible()
  await expect(page.locator('.cm-python-semantic-function').first()).toBeVisible()
  await page.screenshot({ path: 'test-results/python-editor-light.png', fullPage: true })
  await page.evaluate(() => document.documentElement.classList.add('dark'))
  await expect(page.locator('.cm-editor').first()).toHaveCSS('background-color', 'rgb(10, 15, 20)')
  await page.screenshot({ path: 'test-results/python-editor-dark.png', fullPage: true })
  await expect(page.locator('.cm-foldGutter .cm-gutterElement').filter({ hasText: '⌄' }).first()).toBeVisible()
  await page.locator('.cm-foldGutter .cm-gutterElement').filter({ hasText: '⌄' }).first().click()
  await expect(page.locator('.cm-foldPlaceholder')).toBeVisible()
  await page.locator('.cm-foldPlaceholder').click()
  await replace(page, 'from axile.server.context import Context\ndef calculate_portfolio(context: Context):\n    context.get_')
  await page.keyboard.press('Control+Space')
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('get_price')
  await page.keyboard.press('Escape')
  await replace(page, 'wrong: int = "中文😀"\n')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
  await replace(page, 'wrong: int = 1\n')
  await expect(page.getByTestId('problems')).toHaveText('[]')
})

test('auto-import completion inserts an import and is undoable', async ({ page }) => {
  await replace(page, 'path = Pat')
  await page.keyboard.press('Control+Space')
  const option = page.locator('.cm-tooltip-autocomplete li').filter({ hasText: /Path.*pathlib/ }).first()
  await expect(option).toBeVisible()
  await option.click()
  await expect(page.getByTestId('code')).toContainText('from pathlib import Path')
  await expect(page.getByTestId('code')).toContainText('path = Path')
  await page.keyboard.press('ControlOrMeta+z')
  await expect(page.getByTestId('code')).toHaveText('path = Pat')
})

test('a delayed formatter cannot overwrite newer typing', async ({ page }) => {
  let finish: () => void = () => {}
  const waiting = new Promise<void>((resolve) => { finish = resolve })
  await page.route('**/editor/format', async (route) => {
    await waiting
    await route.fulfill({ json: { code: 'value = 1\n' } })
  })
  await replace(page, 'value=1')
  await page.getByRole('button', { name: '格式化', exact: true }).click()
  await expect(page.getByRole('button', { name: '格式化中…' })).toBeDisabled()
  await replace(page, 'value=2')
  finish()
  await expect(page.getByText('代码已变化，请重新格式化')).toBeVisible()
  await expect(page.getByTestId('code')).toHaveText('value=2')
})

test('definition opens read-only source and rename is undoable', async ({ page }) => {
  await page.locator('.cm-content').first().click()
  await page.keyboard.press('ControlOrMeta+Home')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Home')
  for (let i = 0; i < 24; i++) await page.keyboard.press('ArrowRight')
  await page.keyboard.press('F12')
  await expect(page.getByRole('dialog', { name: '只读源码预览' })).toBeVisible()
  await expect(page.getByRole('dialog')).toContainText('context.py')
  await expect(page.getByRole('dialog').locator('.cm-content')).toHaveAttribute('contenteditable', 'false')
  await page.keyboard.press('Escape')
  await expect(page.locator('.cm-content').first()).toBeFocused()
  await page.keyboard.press('Home')
  for (let i = 0; i < 2; i++) await page.keyboard.press('ArrowRight')
  await page.keyboard.press('Shift+F12')
  await expect(page.locator('.cm-lsp-reference')).toHaveCount(2)
  await page.keyboard.press('Escape')
  await page.keyboard.press('F2')
  await page.locator('input[name=name]').fill('latest_price')
  await page.getByRole('button', { name: '重命名', exact: true }).last().click()
  await expect(page.getByTestId('code')).toContainText('latest_price')
  await page.keyboard.press('ControlOrMeta+z')
  await expect(page.getByTestId('code')).not.toContainText('latest_price')
})

test('hover, signature help and quick fixes use ty results', async ({ page }) => {
  await page.locator('.cm-python-semantic-method, .cm-python-semantic-function').filter({ hasText: /^get_price$/ }).hover()
  await expect(page.locator('.cm-tooltip')).toContainText('get_price')
  await replace(page, 'from axile.server.context import Context\ndef calculate_portfolio(context: Context):\n    context.get_price')
  await page.keyboard.type('(')
  await expect(page.locator('.cm-tooltip')).toContainText('symbol')
  await replace(page, 'wrong: int = "bad"')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
  await editorCommand(page, '快速修复')
  const fixes = page.locator('form[aria-label="快速修复"] button')
  await expect(fixes.first()).toBeVisible()
  await fixes.first().click()
  await expect(page.getByTestId('code')).not.toHaveText('wrong: int = "bad"')
  await editorCommand(page, '撤销')
  await expect(page.getByTestId('code')).toHaveText('wrong: int = "bad"')
})

test('runtime diagnostics coexist with ty and expire after editing', async ({ page }) => {
  await replace(page, 'wrong: int = "bad"')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
  await page.keyboard.press('ControlOrMeta+Enter')
  await expect(page.getByTestId('problems')).toContainText('模拟试跑错误')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
  await page.keyboard.type(' ')
  await expect(page.getByTestId('problems')).not.toContainText('模拟试跑错误')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
})

test('indentation, bracket pairing, comment and multi-selection shortcuts', async ({ page }) => {
  await replace(page, 'def example():')
  await page.keyboard.press('Enter')
  await page.keyboard.type('value = (')
  await expect(page.getByTestId('code')).toHaveText('def example():\n    value = ()')
  await page.keyboard.press('ControlOrMeta+/')
  await expect(page.getByTestId('code')).toContainText('# value = ()')
  await replace(page, 'value = 1\nother = value')
  await page.keyboard.press('ControlOrMeta+Home')
  await page.keyboard.press('ControlOrMeta+d')
  await page.keyboard.press('ControlOrMeta+d')
  await page.keyboard.insertText('price')
  await expect(page.getByTestId('code')).toHaveText('price = 1\nother = price')
})

test('reconnect resynchronizes unsaved text without losing undo', async ({ page, request }) => {
  await replace(page, 'draft: int = "keep me"\n')
  await request.post('http://127.0.0.1:1439/test/disconnect')
  await expect(page.getByRole('status', { name: '代码分析器' })).toHaveAttribute('data-state', 'reconnecting')
  await expect(page.getByRole('status', { name: '代码分析器' })).toHaveAttribute('data-state', 'ready', { timeout: 20000 })
  await expect(page.getByTestId('code')).toHaveText('draft: int = "keep me"\n')
  await expect(page.getByTestId('problems')).toContainText('not assignable')
  await editorCommand(page, '撤销')
  await expect(page.getByTestId('code')).not.toContainText('keep me')
})

for (const theme of ['light', 'dark']) {
  test(`shortcut hints stay readable and accessible in ${theme} and narrow menus`, async ({ page }) => {
    await page.evaluate((theme) => { document.documentElement.classList.toggle('dark', theme === 'dark') }, theme)
    const format = page.getByRole('button', { name: '格式化', exact: true })
    await expect(format).toContainText('Shift+Alt+F')
    const hint = format.locator('span')
    const colors = await hint.evaluate((node) => ({ hint: getComputedStyle(node).color, label: getComputedStyle(node.parentElement!).color, size: parseFloat(getComputedStyle(node).fontSize), labelSize: parseFloat(getComputedStyle(node.parentElement!).fontSize) }))
    expect(colors.hint).not.toBe(colors.label)
    expect(colors.size).toBeLessThan(colors.labelSize)
    await page.setViewportSize({ width: 375, height: 720 })
    await expect(format).toBeHidden()
    const trigger = page.getByRole('button', { name: '菜单', exact: true })
    await trigger.click()
    await expect(trigger).toHaveAttribute('aria-expanded', 'true')
    await expect(page.getByText('快捷键说明', { exact: true })).toHaveCount(0)
    const rename = page.getByRole('menuitem', { name: '重命名', exact: true })
    await expect(rename).toContainText('F2')
    await expect(page.getByRole('menuitem', { name: '粘贴', exact: true }).locator('span')).toHaveCount(1)
    const bounds = await page.getByRole('menu').boundingBox()
    expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(375)
    await page.keyboard.press('Escape')
    await replace(page, 'value=1\n')
    await page.keyboard.press('Shift+Alt+f')
    await expect(page.getByTestId('code')).toHaveText('value = 1\n')
    await page.keyboard.press('ControlOrMeta+z')
    await expect(page.getByTestId('code')).toHaveText('value=1\n')
    await page.keyboard.press(process.platform === 'darwin' ? 'Meta+Shift+z' : 'Control+y')
    await expect(page.getByTestId('code')).toHaveText('value = 1\n')
  })
}

test('Mac menus show Command shortcuts', async ({ page }) => {
  await page.addInitScript(() => Object.defineProperty(navigator, 'platform', { get: () => 'MacIntel' }))
  await page.reload()
  await page.getByRole('button', { name: '菜单', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: '撤销', exact: true })).toContainText('⌘+Z')
  await expect(page.getByRole('menuitem', { name: '重做', exact: true })).toContainText('⌘+Shift+Z')
  await expect(page.getByRole('menuitem', { name: '查找 / 替换', exact: true })).toContainText('⌘+F')
})

test('long hover documentation stays bounded, scrolls, resizes and supports keyboard focus', async ({ page }) => {
  const paragraphs = Array.from({ length: 60 }, (_, i) => `    Paragraph ${i}: ${'Documentation detail '.repeat(15)}`).join('\n\n')
  await replace(page, `def documented(value: str) -> str:\n    """Long documentation.\n\n${paragraphs}\n\n    ${'long_identifier_'.repeat(100)}\n    """\n    return value\n`)
  await page.keyboard.press('ControlOrMeta+Home')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ControlOrMeta+Alt+i')
  const doc = page.getByRole('region', { name: 'Python 文档' })
  await expect(doc).toBeVisible()
  await expect(doc).toBeFocused()
  const bounds = await doc.boundingBox()
  expect(bounds!.height).toBeLessThanOrEqual(420)
  expect(await doc.evaluate(el => el.scrollHeight > el.clientHeight)).toBe(true)
  await page.keyboard.press('PageDown')
  await expect.poll(() => doc.evaluate(el => el.scrollTop)).toBeGreaterThan(0)
  await doc.hover()
  await page.mouse.wheel(0, 500)
  await expect(doc).toBeVisible()
  const frame = page.locator('.cm-python-hover')
  const before = await frame.boundingBox()
  const handle = await page.locator('.cm-python-hover-resize').boundingBox()
  await page.mouse.move(handle!.x + 7, handle!.y + 7)
  await page.mouse.down()
  await page.mouse.move(handle!.x - 93, handle!.y + 57, { steps: 5 })
  await page.mouse.up()
  await expect.poll(async () => (await frame.boundingBox())!.width).toBeLessThan(before!.width - 50)
  const resized = (await frame.boundingBox())!.width
  await doc.focus()
  await page.keyboard.press('Escape')
  await expect(doc).toHaveCount(0)
  await expect(page.locator('.cm-content').first()).toBeFocused()
  await page.keyboard.press('ControlOrMeta+Alt+i')
  await expect(doc).toBeVisible()
  expect(Math.abs((await frame.boundingBox())!.width - resized)).toBeLessThan(3)
  await page.setViewportSize({ width: 420, height: 320 })
  await expect.poll(async () => {
    const box = await doc.boundingBox()
    return !!box && box.x >= 0 && box.y >= 0 && box.x + box.width <= 420 && box.y + box.height <= 320
  }).toBe(true)
  expect(await doc.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
})

test('mouse hover remains readable above the anchor and resizes upwards', async ({ page }) => {
  await page.setViewportSize({ width: 900, height: 600 })
  await replace(page, `${'\n'.repeat(16)}def documented():\n    """${'A long documentation paragraph. '.repeat(250)}"""\n    pass\n`)
  const name = page.locator('.cm-python-semantic-function').filter({ hasText: /^documented$/ }).first()
  await name.hover()
  const doc = page.getByRole('region', { name: 'Python 文档' })
  await expect(doc).toBeVisible()
  await expect(page.locator('.cm-tooltip-hover')).toHaveClass(/cm-tooltip-above/)
  await doc.hover()
  await page.mouse.wheel(0, 400)
  await expect.poll(() => doc.evaluate(el => el.scrollTop)).toBeGreaterThan(0)
  const frame = page.locator('.cm-python-hover')
  const before = (await frame.boundingBox())!
  const handle = (await page.locator('.cm-python-hover-resize').boundingBox())!
  await page.mouse.move(handle.x + 7, handle.y + 7)
  await page.mouse.down()
  await page.mouse.move(handle.x + 7, handle.y + 47, { steps: 5 })
  await page.mouse.up()
  await expect.poll(async () => (await frame.boundingBox())!.height).toBeLessThan(before.height - 20)
  await doc.focus()
  await page.keyboard.press('Escape')
  await expect(doc).toHaveCount(0)
})

test('hover pins its signature and pushes section headings away as the next section enters', async ({ page }) => {
  const paragraphs = Array.from({ length: 12 }, (_, i) => `    Detail ${i}: ${'Documentation text. '.repeat(6)}`).join('\n\n')
  await replace(page, `def documented(value: str) -> str:\n    """Summary.\n\n    ## Parameters\n\n${paragraphs}\n\n    ## Returns\n\n${paragraphs}\n    """\n    return value\n`)
  await page.keyboard.press('ControlOrMeta+Home')
  for (let i = 0; i < 5; i++) await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ControlOrMeta+Alt+i')
  const doc = page.getByRole('region', { name: 'Python 文档' })
  const signature = page.getByRole('region', { name: '函数签名' })
  await expect(signature).toContainText('documented')
  const signatureBefore = (await signature.boundingBox())!
  expect(await signature.evaluate(el => el.scrollHeight <= el.clientHeight + 1)).toBe(true)
  await signature.hover()
  await page.mouse.wheel(0, 180)
  await expect.poll(() => doc.evaluate(el => el.scrollTop)).toBeGreaterThan(100)
  const parameters = doc.getByRole('heading', { name: 'Parameters' })
  const returns = doc.getByRole('heading', { name: 'Returns' })
  await expect.poll(async () => Math.abs((await parameters.boundingBox())!.y - (await doc.boundingBox())!.y)).toBeLessThan(2)
  expect((await signature.boundingBox())!.y).toBe(signatureBefore.y)
  expect(await signature.evaluate(el => {
    const frame = el.getBoundingClientRect()
    const text = el.querySelector('code')!.getBoundingClientRect()
    return text.top >= frame.top && text.bottom <= frame.bottom
  })).toBe(true)
  // Stop with the next heading halfway through the sticky heading's slot.
  await doc.evaluate(el => {
    const heading = el.querySelectorAll('h2')[1]
    el.scrollTop += heading.getBoundingClientRect().top - el.getBoundingClientRect().top - 12
  })
  await expect.poll(async () => (await parameters.boundingBox())!.y).toBeLessThan((await doc.boundingBox())!.y)
  await doc.evaluate(el => { el.scrollTop += 100 })
  await expect.poll(async () => Math.abs((await returns.boundingBox())!.y - (await doc.boundingBox())!.y)).toBeLessThan(2)
  expect((await signature.boundingBox())!.y).toBe(signatureBefore.y)
  await page.setViewportSize({ width: 420, height: 320 })
  await expect(doc).toBeVisible()
  expect((await doc.boundingBox())!.height).toBeGreaterThan(40)
  expect(await signature.evaluate(el => el.scrollHeight <= el.clientHeight + 1)).toBe(true)
  await doc.focus()
  await page.keyboard.press('Escape')
  await expect(doc).toHaveCount(0)
})

test('editor sticky scroll shows nested scopes, follows horizontal scroll and jumps to declarations', async ({ page }) => {
  const body = Array.from({ length: 45 }, (_, i) => `            print(${i})`).join('\n')
  const next = Array.from({ length: 45 }, (_, i) => `    print(${i})`).join('\n')
  const parameters = Array.from({ length: 20 }, (_, i) => `_parameter_number_${i}=0`).join(', ')
  await replace(page, `class Strategy:\n    def calculate(self, ${parameters}):\n        if True:\n${body}\n\ndef another():\n${next}\n`)
  const scroller = page.locator('.cm-scroller').first()
  const sticky = page.getByRole('navigation', { name: '代码作用域' }).first()
  await scroller.evaluate(el => { el.scrollTop = 0 })
  await expect(sticky).toBeHidden()
  await scroller.hover()
  await page.mouse.wheel(0, 350)
  await expect(sticky.getByRole('button')).toHaveCount(3)
  await expect(sticky).toContainText('class Strategy:')
  await expect(sticky).toContainText('def calculate(self,')
  await expect(sticky).toContainText('if True:')
  const rect = (await sticky.boundingBox())!
  const scrollRect = (await scroller.boundingBox())!
  expect(Math.abs(rect.y - scrollRect.y)).toBeLessThan(2)
  const initialScroll = await scroller.evaluate(el => el.scrollTop)
  await sticky.hover()
  await page.mouse.wheel(0, 100)
  await expect.poll(() => scroller.evaluate(el => el.scrollTop)).toBeGreaterThan(initialScroll + 50)
  const code = sticky.locator('.cm-python-sticky-code').nth(1)
  const codeLeft = (await code.boundingBox())!.x
  const gutterLeft = (await sticky.locator('.cm-python-sticky-number').nth(1).boundingBox())!.x
  await scroller.evaluate(el => { el.scrollLeft = 120 })
  await expect.poll(async () => (await code.boundingBox())!.x).toBeLessThan(codeLeft - 100)
  expect((await sticky.locator('.cm-python-sticky-number').nth(1).boundingBox())!.x).toBe(gutterLeft)
  await scroller.evaluate(el => { el.scrollLeft = 0 })
  await page.screenshot({ path: '/tmp/axon-editor-sticky-nested.png' })
  await sticky.getByRole('button', { name: /第 2 行/ }).click()
  await expect(page.locator('.cm-content').first()).toBeFocused()
  await expect.poll(() => scroller.evaluate(el => el.scrollTop)).toBeLessThan(80)
  await scroller.evaluate(el => { el.scrollTop = 1300 })
  await expect(sticky.getByRole('button')).toHaveCount(1)
  await expect(sticky).toContainText('def another():')
  await expect(sticky).not.toContainText('Strategy')
  await page.screenshot({ path: '/tmp/axon-editor-sticky.png' })
  await replace(page, 'value = 1\n')
  await expect(sticky).toBeHidden()
})
